### ISSUE TITLE
Craft installation

### ISSUE THREAD

**Issue by leightonhughes** [timkelty/craftcms-docker-compose#1]
Thanks for setting this up Tim.
Took me a little while connecting to the DB as didn’t have DB_SERVER set to postgre as I usually go mysql. Perhaps an environment file that is filled out would be helpful to others with this beginner mistake :).

Were there any key differences with your default craft files in making it work in comparison to https://github.com/craftcms/docker?

Am I correct in saying that the line below is is going inside the container and installing vendor directory?
```
docker-compose run --rm console composer install
```

**Comment by timkelty** [comment]
> environment file that is filled out would be helpful to others with this beginner mistake :).

Good catch, and yes…we are working on better examples.

> Were there any key differences with your default craft files in making it work in comparison to https://github.com/craftcms/docker?

`craftcms/docker` is the source for the actual docker images. This repo is just an example of using those docker images via docker-compose.

> Am I correct in saying that the line below is is going inside the container and installing vendor directory?

Yep, it is running `composer install` inside the `console` container. In this example, we are bind-mounting the entire project directory, so the resulting `vendor/` files will also show up on your host machine.

**Comment by timkelty** [comment]
@leightonhughes I just pushed a tweak to the env vars to avoid confusion like you had.

**Comment by leightonhughes** [comment]
Awesome, thanks @timkelty. Just one more question. On running docker-compose up -d my containers are starting and running except for craftcms/nginx:8.0-dev. If I manually click the container start button in the docker desktop app it starts running and works. Would this be because of it depending on postgres and redis in the compose file?

**Comment by timkelty** [comment]
Could be. Try running `docker-compose logs postgres` to see why a given container isn't starting. If you post your entire compose file, I can see what's going on better.

**Comment by leightonhughes** [comment]
Thanks for that. Just needed to wait longer and it started. Just figured out what the -d "detached" flag does too. 👍

**Comment by timkelty** [comment]
FWIW - what is causing the delay is the `condition: service_healthy`/ `healthcheck` stuff. You don't _have_ to have that there, but it exists to prevent confusion on startup when required services haven't boot up yet.
