### ISSUE TITLE
relation "info" does not exist at character 15

### ISSUE THREAD

**Issue by riccardolardi** [timkelty/craftcms-docker-compose#2]
I do still get the `relation "info" does not exist at character 15` error in the postgres service even with this setup. Any idea what could be wrong? Thanks!

**Comment by riccardolardi** [comment]
I figured out this error seems can be ignored - it's possible to just install craft either by exec into web service or just web interface. It then works fine. Closing :)

**Comment by timkelty** [comment]
@riccardolardi When do you see that? When you hit the http://localhost:8080/admin page?
If you're trying to run a craft command (eg `craft db/restore`), you can get that error if you have an empty database.

**Comment by riccardolardi** [comment]
@timkelty yes I was seeing it before having installed Craft into the DB...
